version: '2'
services:
  redis:
    build: ./redis
    expose:
      - "6379"
    restart: ${RESTART_POLICY}
  db:
    build: ./mysql
    #command: --default-authentication-plugin=mysql_native_password 
    expose:
      - "3306"
    volumes:
      - ~/tmp/kegbot/db:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=kebgot-db-pass
#      - MYSQL_ROOT_HOST=%
    restart: ${RESTART_POLICY}

  server:
    build: ./server
    links:
      - db:db.docker
      - redis:redis.docker
    volumes:
      - ~/tmp/kegbot/server:/kegbot-data:rw
    environment:
      - KEGBOT_DB_HOST=db.docker
      - KEGBOT_REDIS_HOST=redis.docker
      - KEGBOT_SETTINGS_DIR=/etc/kegbot/
      - KEGBOT_DB_PASS=kebgot-db-pass
      - KEGBOT_DEBUG='true'
    expose:
      - "8000"
    restart: ${RESTART_POLICY}
  nginx:
    build: ./nginx
    links:
      - server:kegbot.docker
    volumes:
      - ~/tmp/kegbot/server:/kegbot-data:ro
      - ./nginx/kegbot.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: ${RESTART_POLICY}

